<?php 
/*
 * all custom code write here.
 */

/*
 * Implements hook_views_query_alter.
 */
function chomchom_views_views_query_alter(&$view, &$query){
  //Alter query for all category page 
  if ((($view->name == 'can_tho') && ($view->current_display == 'page')) || 
    (($view->name == 'can_tho') && ($view->current_display == 'block_1')) || 
    (($view->name == 'can_tho_toc') && ($view->current_display == 'page')) || 
    (($view->name == 'can_tho_toc') && ($view->current_display == 'block_1'))||
    (($view->name == 'quang_cao_rao_vat') && ($view->current_display == 'page')) ||
    (($view->name == 'quang_cao_rao_vat') && ($view->current_display == 'block_1'))||
    (($view->name == 'sang_tiem_nails') && ($view->current_display == 'page'))||
    (($view->name == 'sang_tiem_nails') && ($view->current_display == 'block_1'))||
    (($view->name == 'business_for_sale') && ($view->current_display == 'page'))||
    (($view->name == 'business_for_sale') && ($view->current_display == 'block_1'))||
    (($view->name == 'business_directory') && ($view->current_display == 'page'))||
    (($view->name == 'business_directory') && ($view->current_display == 'block_1'))
    ) {
   /* print('<pre style="color:red;">');
    print_r($_SESSION);
    print('</pre>');
    exit;*/

    //check in country code set in session
    if(isset($_SESSION['smart_ip']['location']['country_code']) && !empty($_SESSION['smart_ip']['location']['country_code'])){

      //get country code
      $country_shortcode = $_SESSION['smart_ip']['location']['country_code'];

      //capitalize country code
      $country_short =strtolower($country_shortcode);

      //load all inc file from location module using country code
      $data = module_load_include('inc', 'location', 'supported/location.'.$country_short);

      //load function from using country code 
      $strfun = 'location_province_list_'.$country_short;
      $callfunction = $strfun();

      //check region set in session
      if((isset($_SESSION['smart_ip']['location']['region'])) && (!empty($_SESSION['smart_ip']['location']['region']))){

        //find country code from country field
        $state_short = array_search($_SESSION['smart_ip']['location']['region'],$callfunction);
        //check filter set
        if((isset($query->where[1]['conditions'])) && (!empty($query->where[1]['conditions']))){
          $filter = $query->where[1]['conditions'];

          //set loop for all filter
          foreach ($filter as $key => $value) {

            //check state field
            if($value['field'] == 'location.province'){

              //set state code in filter value
              $query->where[1]['conditions'][$key]['value']	= $state_short;
            }
          }
        }	
      }else{//otherwise remove filter
        //check filter set
        if((isset($query->where[1]['conditions'])) && (!empty($query->where[1]['conditions']))){
          $filter = $query->where[1]['conditions'];
          //set loop for all filter
          foreach ($filter as $key => $value) {	

            //check state field		
            if($value['field'] == 'location.province'){

              //unset state filter
              unset($query->where[1]['conditions'][$key]);
            }
          }
        }
      }
    }
  }
  if ((($view->name == 'can_tho') && ($view->current_display == 'page')) ||
  (($view->name == 'can_tho_toc') && ($view->current_display == 'page')) ||
  (($view->name == 'quang_cao_rao_vat') && ($view->current_display == 'page')) ||
  (($view->name == 'sang_tiem_nails') && ($view->current_display == 'page'))||
  (($view->name == 'business_directory') && ($view->current_display == 'page'))||
  (($view->name == 'business_for_sale') && ($view->current_display == 'page')))
   {
    if (isset($_REQUEST['sort_order']) && !empty($_REQUEST['sort_order'])) {
      if ($_REQUEST['sort_order'] == 'RAND') {
        $query->orderby[0]['field'] = 'rand_';
        $query->orderby[0]['direction']='ASC';
      }
    }
  } 
}

/*
 * Implement hook_form_alter. 
 */

function chomchom_views_form_alter(&$form, $form_state, $form_id) {
  // check views exposed form
  if($form_id == 'views_exposed_form'){

    //check in country code set in session
    if(isset($_SESSION['smart_ip']['location']['country_code']) && !empty($_SESSION['smart_ip']['location']['country_code'])){
      //get country code
      $country_shortcode = $_SESSION['smart_ip']['location']['country_code'];

      //capitalize country code
      $country_short =strtolower($country_shortcode);

      //load all inc file from location module using country code
      $data = module_load_include('inc', 'location', 'supported/location.'.$country_short);

      //load function from using country code 
      $strfun = 'location_province_list_'.$country_short;
      $callfunction = $strfun();

      //find country code from country field
      $state_short = array_search($_SESSION['smart_ip']['location']['region'],$callfunction);

      //set defult user state name in state field 
      $form['province']['#default_value']= $state_short;
    }
  }

  if (isset($_SESSION['nid']) && !empty($_SESSION['nid'])){
      // check form id and if true then
    $newstring = $form_id;
    $pos = strpos($newstring, 'commerce_cart_add_to_cart_form_');
    if ($pos !== false) {
      $query = new EntityFieldQuery();

      $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'listing')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->fieldCondition('field_featured_date', 'value', '', '!=');
        $result = $query->execute();

      if (isset($result['node'])) {
        $news_items_nids = array_keys($result['node']);
        $news_items = entity_load('node', $news_items_nids);
        $count = '0';
        $node = node_load($_SESSION['nid']);
          if (isset($node->field_category[LANGUAGE_NONE]) && !empty($node->field_category[LANGUAGE_NONE])) {
            $node_tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
            //call function get parent
            $result = chomchom_views_get_parent($node_tid);
          }
          if (isset($node->locations[0]) && !empty($node->locations[0])) {
            $node_province = $node->locations[0]['province'];
          }
        foreach ($news_items as $key => $value) { 

          if (isset($value->field_category[LANGUAGE_NONE]) && !empty($value->field_category[LANGUAGE_NONE]) && isset($value->locations[0]) && !empty($value->locations[0])) {
              //call function get parent
              $get_parent = chomchom_views_get_parent($value->field_category[LANGUAGE_NONE][0]['tid']);    
            if (($get_parent == $result) && ($value->locations[0]['province'] == $node_province)) {
              $count ++;
            } 
          }    
        }
        if ($count >= 5) {
          unset($form['attributes']['field_featured']);
        }
      }
    }
  }
}


/*
 * Implement custom function for get parent id
 */
function chomchom_views_get_parent($tid){
  $parenttid = taxonomy_get_parents($tid);
  if (isset($parenttid) && !empty($parenttid)) {
    foreach ($parenttid as $key => $value) {
      $pare_tid = $value->tid;
    }   
  }
  else {
    $pare_tid = $tid;
  }
  return $pare_tid;
}


/*
 * Implement hookform_views_exposed_form_alter. 
 */
function chomchom_views_form_views_exposed_form_alter(&$form, &$form_state){
  if(($form['#id'] == 'views-exposed-form-can-tho-page') ||
    ($form['#id'] == 'views-exposed-form-can-tho-toc-page') ||
    ($form['#id'] == 'views-exposed-form-sang-tiem-nails-page') ||
    ($form['#id'] == 'views-exposed-form-business-for-sale-page') ||
    ($form['#id'] == 'views-exposed-form-business-directory-page') ||
    ($form['#id'] == 'views-exposed-form-quang-cao-rao-vat-page')){
    $form['sort_order']['#options']['ASC'] = 'Oldest to Newest';
    $form['sort_order']['#options']['DESC'] = 'Newest to Oldest';
    $form['sort_order']['#options']['RAND'] = 'Random';
  }
}