<?php 
/*
 * all custom code write here.
 */


/*
 * Implements custom function for twilio configration
 */
function twilio_configration() {
  $path = libraries_get_path('twilio');
  require($path . "/Services/Twilio.php");
  $accountSID = variable_get('twilio_account');
  $authToken = variable_get('twilio_token');
  $client = new Services_Twilio($accountSID, $authToken);
  return $client;
}


/*
 * Implements custom function for body text
 */
function body_text($nodevalue,$value='') {
  global $base_url;
  $alias = drupal_get_path_alias('node/'.$nodevalue->nid);
  $url = $base_url .$alias;
  if(isset($value) && !empty($value)){
    $data = 'Thank you for posting your ad with chomchom.net';
    $data .= $url;
    $data .= 'Your ad will expires in '.$value.' days.';
    $data .= 'We will send you notifications before your ad expires.';
  }else{
    $data = 'Your ads will expire';
  }
  return $data;
}


/*
 * Implements custom function for body text mail
 */
function mail_body_text($nodevalue,$value='') {
  global $base_url;
  $alias = drupal_get_path_alias('node/'.$nodevalue->nid);
  $url = $base_url .$alias;
  if(isset($value) && !empty($value)){
    $data = 'Thank you for posting your ad with chomchom.net'.'</br>';
    $data .= $url.'</br>';
    $data .= 'Your ad will expires in '.$value.' days.'.'</br>';
    $data .= 'We will send you notifications before your ad expires.'.'</br>';
    $data .= 'If you have any questions, please call us Monday-Friday 10 a.m.-8 p.m. EST at 404-884-1888 FREE or email raovat@chomchom.net.'.'</br>';
    $data .= 'We wish you the best of luck, and thanks again for using ChomChom.net.'.'</br>';
    $data .= 'Warm Regards,'.'</br>';
    $data .= 'chomchom.net'.'</br>';
    $data .= 'http://www.chomchom.net'.'</br>';
  }else{
    $data = 'Your ads will expire';
  }
  return $data;
}

/*
 * Implements custom function for sms
 */
function sms_send($nodevalue,$value=''){

  $user = user_load($nodevalue->uid);
  if (isset($user->twilio_user) && !empty($user->twilio_user)) {
    $client = twilio_configration();
    $from = variable_get('twilio_number');
    $phone_numbers = '+'.$user->twilio_user['country'].$user->twilio_user['number'];
    try{
    $message = $client->account->messages->create(array(
        "From" => $from,
        "To" => $phone_numbers,
        "Body" => body_text($nodevalue,$value),
    ));
    // Display a confirmation message on the screen
    echo "Sent message";
    }catch (Exception $e) {
        echo 'Error: ' . $e->getMessage();
    } 
  }
}


/*
 * Implements custom function for message
 */
function message_send($nodevalue,$value=''){
  $user = user_load($nodevalue->uid);
  $to = $user->mail; // to e-mail address
  $from = variable_get('site_mail'); // from e-mail address

  $subject = "We will send you notifications before your ad expires."; // subject of e-mail
  //params is the array passed to hook_mail function 
  $params = array(
    'subject' => $subject,
    'body' => mail_body_text($nodevalue,$value),
  );
  drupal_mail('chomchom_general', 'information', $to, language_default(), $params, $from);  
}


/*
 * Implements hook_cron.
 */
function chomchom_general_cron() {
  //Get today date 
  $todate = date('Y-m-d');

  //load listing type all publish node
  $nodes = node_load_multiple(array(), array('type' => 'listing','status' => 1));
  foreach($nodes as $nodekey => $nodevalue){

    //featured date set then check today and featured same then black featured date field
    if (isset($nodevalue->field_featured_date[LANGUAGE_NONE]) && !empty($nodevalue->field_featured_date[LANGUAGE_NONE])) {
      $fdate = explode(" ",$nodevalue->field_featured_date['und'][0]['value']);
      if($todate > $fdate[0]){
        unset($nodevalue->field_featured_date['und']);
        node_save($nodevalue);
      }
    }

    //check expire date set
    if (isset($nodevalue->field_expire_date[LANGUAGE_NONE]) && !empty($nodevalue->field_expire_date[LANGUAGE_NONE])) {
      $edate = explode(" ",$nodevalue->field_expire_date[LANGUAGE_NONE][0]['value']);

      $days = array("10", "5", "1");
      foreach ($days as $key => $value) {
        $expiredate = date('Y-m-d', strtotime($edate[0]."-".$value." days"));

        if ($expiredate == $todate) {     
          message_send($nodevalue,$value);
          sms_send($nodevalue,$value);
        }
      }

      //todat date and expire date same then unpublish node
      if ($todate == $edate[0] ){
        sms_send($nodevalue);
        message_send($nodevalue);
        $nodevalue->status = '0';        
        node_save($nodevalue);
      }

      //last update node after 10 day node delete 
      $last_update = date('Y-m-d', $nodevalue->changed);
      $passdate = date('Y-m-d', strtotime($last_update."+10 days"));
      if ($todate == $passdate ){
        node_delete($nodevalue->nid);
      }
    } 
  }
}

