<?php 

/*
 *@file
 * commerce custom code write here.
 */

/*
 * After submit set nid to session
 */
/*
function chomchom_commerce_node_insert($node) {
  //set nid to session
  $_SESSION['nid'] = $node->nid;
  if(isset($node->field_category[LANGUAGE_NONE]) && !empty($node->field_category[LANGUAGE_NONE])){
    $form_tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
    /* 
     * 1.can tho,2.can tho nails,3.can tho toc,
     * 4.sang tiem,5.sang tiem nails,6.business for sale,
     * 7.Quang Cao & Rao Vat ,8. Business Directory
     */
    /*switch ($form_tid) {
      case '1':
      case '2':
      case '3':
          drupal_goto('node/13');
          break;
      case '4':
      case '5':
      case '6':
          drupal_goto('node/14');
          break;
      case '7':
          drupal_goto('node/15');
          break;
      case '8':
          drupal_goto('node/16');
          break;
      default:
          break;
    } 
  }
}


/*
 * Implement hook_commerce_checkout_complete 
 */
function chomchom_commerce_commerce_checkout_complete($order) {
  //Get line item id
  $commercelineid = $order->commerce_line_items[LANGUAGE_NONE][0]['line_item_id'];
  //load line item from line item id
  $lineitem = commerce_line_item_load($commercelineid);
  //get product id from line item
  $productid = $lineitem->commerce_product[LANGUAGE_NONE][0]['product_id'];
  //load commerce product from product id
  $commerce_product = commerce_product_load($productid);
  //Get tid form commerce product
  $month_tid = $commerce_product->field_month[LANGUAGE_NONE][0]['tid'];
  //Get term from tid
  $term = taxonomy_term_load($month_tid);
  $termname = $term->name;
  //On tid calculate date for expire 
  if ($month_tid == '12' || $month_tid == '13') {
    $month_date = date('Y-m-d', strtotime("+100  year"));
  }
  else {
    $month_date = date('Y-m-d', strtotime("+".$termname));
  }
  //if featured date set then set featured date
  if (isset($commerce_product->field_featured[LANGUAGE_NONE]) && !empty($commerce_product->field_featured[LANGUAGE_NONE])) {
    $featured_tid = $commerce_product->field_featured[LANGUAGE_NONE][0]['tid'];
    $featureterm = taxonomy_term_load($featured_tid);
    $featuretermname = $featureterm->name;
    $featured_date = date('Y-m-d',strtotime("+".$featuretermname));
  }
  //if nid set in session then load it and publish it
  if (isset($_SESSION['nid']) && !empty($_SESSION['nid'])) {
    $node = node_load($_SESSION['nid']);
    $node->status = '1';
    if(isset($featured_date) && !empty($featured_date)){
    	$node->field_featured_date[LANGUAGE_NONE][0]['value'] = $featured_date;
    }
    $node->field_expire_date[LANGUAGE_NONE][0]['value'] = $month_date;
    node_save($node);

    global $base_url;
    $alias = drupal_get_path_alias('node/'.$node->nid);
    $url = $base_url .$alias;
    $user = user_load($node->uid);
    $tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
    $category_name = taxonomy_term_load($tid);
      $to = $user->mail; // to e-mail address
      $from = variable_get('site_mail'); // from e-mail address

      $subject = $node->title;
      $data = 'Thank you for placing an ad with us. Your ad is now live at'.$url.'</br>';
      $data .= 'Your ad '.$node->title.' will run for '.$node->field_expire_date[LANGUAGE_NONE][0]['value'].' . We will send you notifications before your ad expires'.'</br>';
      $data .= 'Your Ad Summary'.'</br>';
      $data .= 'Ad Type:'.$category_name->name.'</br>';
      $data .= $node->field_expire_date[LANGUAGE_NONE][0]['value'].'</br>';
      $data .= 'Your ad runs for'.$node->field_expire_date[LANGUAGE_NONE][0]['value'].' . Well send you an email reminders ten, five, & one days before your ad expires.'.'</br>';
      $data .= 'You may edit or remove all your listings here:'.$url.'</br>';
      $data .= $url.': When you click edit you will be able to:'.'</br>';
      $data .= 'Edit your description'.'</br>';
      $data .= 'Edit other ad details'.'</br>';
      $data .= 'Edit your contact info'.'</br>';

      $data .= 'If you have any questions, please call us Monday-Friday 10 a.m.-8 p.m. EST at 404-884-1888 FREE or email raovat@chomchom.net.'.'</br>';
      $data .= 'We wish you the best of luck, and thanks again for using ChomChom.net.'.'</br>';
      $data .= 'Warm Regards,'.'</br>';
      $data .= 'chomchom.net'.'</br>';
      $data .= 'http://www.chomchom.net'.'</br>';
  //params is the array passed to hook_mail function 
      $params = array(
        'subject' => $subject,
        'body' => $data,
      );
  drupal_mail('chomchom_general', 'information', $to, language_default(), $params, $from);

  }
}


/*
 * Implement template_preprocess_page 
 */

function chomchom_commerce_preprocess_page(&$variables) {
  if(isset($variables['node']) && !empty($variables['node'])) {
    if ($variables['node']->type == 'product_display') {
      if (isset($_GET['nid']) && !empty($_GET['nid'])){
        $_SESSION['nid'] = $_GET['nid'];
      }
    }
  } 
}
function chomchom_commerce_preprocess_html(&$variables) {
  $node = node_load(arg(1));
  if (isset($node->type) && !empty($node->type)) {
    if ($node->type == 'listing') {
    $tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
    $variables['classes_array'][] = "taxonomy-".$tid;
    }
  } 
}

